apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: petrosa-strategy-gapfinder-backtesting-deploy
  namespace: petrosa-apps
  labels:
    app: petrosa-strategy-gapfinder-backtesting-app
spec:
  selector:
    matchLabels:
      app: petrosa-strategy-gapfinder-backtesting
  template:
    metadata:
      labels:
        app: petrosa-strategy-gapfinder-backtesting
    spec:
      containers:
      - name: petrosa-strategy-gapfinder-backtesting
        image: yurisa2/petrosa-strategy-gapfinder-backtesting:latest
        imagePullPolicy: Always
        resources:
          limits:
            # memory: 2G
            cpu: 300m
          requests:
            cpu: 200m
            memory: 200m
        env:
          - name: VERSION
            value: "0.0.8"
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: petrosa-apps-secret
                key: MONGO_URI
                optional: false
          - name: NEW_RELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: petrosa-apps-secret
                key: NEW_RELIC_LICENSE_KEY
                optional: false
